ef - Added get riders and get drivers plus tests
ucsb-cs156-s23/proj-gauchoride-s23-5pm-1 pull request #32
Opened 2023-05-31 18:38 UTC by EKF626

In this PR, we add the ability to get a list of all users designated as "rider" and all users designated as "driver".  To test, use swagger to get toggle the rider and driver status of some users then get riders and get drivers.

2023-05-31 23:55 UTC, TG6S85 commented
Looks like all checks are good to go

2023-05-31 23:55 UTC, TG6S85 reviewed
Looks good

2023-06-01 00:09 UTC, TG6S85 submitted a review, later dismissed
MB

2023-06-01 00:13 UTC, andrewpengucsb requested changes

2023-06-01 00:13 UTC, andrewpengucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/UsersControllerTests.java
> +    allUsers.addAll(Arrays.asList(u1, u2, u3, u4));
Adjust indentation to be consistent with rest of file

2023-06-01 00:13 UTC, andrewpengucsb commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/UsersControllerTests.java
> +    allUsers.addAll(Arrays.asList(u1, u2, u3, u4));
PR is mergable once fixed

2023-06-01 01:05 UTC, andrewpengucsb approved these changes
LGTM

2023-06-01 01:33 UTC, cmfisher606 approved these changes
Get functions and tests look good!

2023-06-01 02:18 UTC, merged