Zach individual rides backend
ucsb-cs156-s23/proj-gauchoride-s23-5pm-1 pull request #34
Opened 2023-05-31 23:37 UTC by zpr-ucsb

Draft PR for testing.

2023-06-04 18:51 UTC, pconrad requested changes
I'm confused by several things:
* What does this class represent? Can you describe the workflow that you have in mind?
* What is the `tripid`?  Typically this implies the existence of a database table called `trips` and a `Trip` object. 
* There are multiple riders, but both from a database standpoint, and a workflow standpoint, I'm confused by that.   Yes, Mike indicated that eventually we would have multiple riders on a trip, but we need a way to support individual rides first, and I'm not clear on what you have in  mind for this feature.

I wonder if it would simplify things to keep things a little closer to the workflow in Mike's spreadsheets for at least the first iteration, and then once we have a full working system.. frontend and backend, for *that* then we iterate to multiple riders etc.

2023-06-04 19:01 UTC, pconrad requested changes
There are access issues that you may need to think through.

And, the description should better explain where this is going... what will be the life cycle of creating one of these objects?  Who creates it: an admin? a driver?

What does the "autorenew" mean?

It looks like some good thought has gone into this, but more of that thought needs to be written down in the description so that we (and future developers) know where you are heading with this.

2023-06-06 21:34 UTC, zpr-ucsb commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/IndividualRidesController.java
> +    // @PreAuthorize("hasRole('ROLE_ADMIN')")
I uncommented all of the pre authorization tests.

2023-06-06 21:35 UTC, zpr-ucsb commented
> I'm confused by several things:
> 
> * What does this class represent? Can you describe the workflow that you have in mind?
> * What is the `tripid`?  Typically this implies the existence of a database table called `trips` and a `Trip` object.
> * There are multiple riders, but both from a database standpoint, and a workflow standpoint, I'm confused by that.   Yes, Mike indicated that eventually we would have multiple riders on a trip, but we need a way to support individual rides first, and I'm not clear on what you have in  mind for this feature.
> 
> I wonder if it would simplify things to keep things a little closer to the workflow in Mike's spreadsheets for at least the first iteration, and then once we have a full working system.. frontend and backend, for _that_ then we iterate to multiple riders etc.



> I'm confused by several things:
> 
> * What does this class represent? Can you describe the workflow that you have in mind?
> * What is the `tripid`?  Typically this implies the existence of a database table called `trips` and a `Trip` object.
> * There are multiple riders, but both from a database standpoint, and a workflow standpoint, I'm confused by that.   Yes, Mike indicated that eventually we would have multiple riders on a trip, but we need a way to support individual rides first, and I'm not clear on what you have in  mind for this feature.
> 
> I wonder if it would simplify things to keep things a little closer to the workflow in Mike's spreadsheets for at least the first iteration, and then once we have a full working system.. frontend and backend, for _that_ then we iterate to multiple riders etc.

2023-06-06 21:36 UTC, zpr-ucsb commented
I went through each of the comments and fixed each one.

1. All of the user authorizations have been uncommented.
2. After discussion with the team we have decided to remove teamId and autorenew fields in the database class. They were initially intended for use in future features we had discussed but we did not end up having time to implement them.

2023-06-06 21:50 UTC, cmfisher606 approved these changes
I like the changes you made to this PR. Looks good!

2023-06-06 21:50 UTC, cmfisher606 approved these changes
I like the changes you made to this PR. Looks good!

2023-06-06 22:49 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/entities/IndividualRides.java
> +  private Long[] riderIds;
I'm still confused about this being an array.

How will will this work in the database?

2023-06-06 22:59 UTC, pconrad requested changes
Still needs some changes, some of which I think I may have pointed out before ...

2023-06-06 22:59 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/IndividualRidesController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
```suggestion
    @PreAuthorize("hasRole('ROLE_DRIVER') || hasRole('ROLE_ADMIN') || hasRole('ROLE_RIDER')")
```

ROLE_USER should not have access any sensitive information, since anyone/everyone with a Google Account has access to ROLE_USER just by logging in.

2023-06-06 22:59 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/IndividualRidesController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
```suggestion
@PreAuthorize("hasRole('ROLE_DRIVER') || hasRole('ROLE_ADMIN') || hasRole('ROLE_RIDER')")
```

2023-06-06 22:59 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/IndividualRidesController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
```suggestion
@PreAuthorize("hasRole('ROLE_DRIVER') || hasRole('ROLE_ADMIN') || hasRole('ROLE_RIDER')")
```

2023-06-06 22:59 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/IndividualRidesController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
```suggestion
@PreAuthorize("hasRole('ROLE_DRIVER') || hasRole('ROLE_ADMIN') || hasRole('ROLE_RIDER')")
```

2023-06-06 22:59 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/entities/IndividualRides.java
> +  private Long[] riderIds;
I checked the database.  It stores this as a "byte array".  That's not going to do what we want.

I suggest that you change this to simply 
```suggestion
  private Long riderId;
```

And make the assumption of one rider per ride for now; and then we can leave multiple riders as work for the summer 2023 students.

2023-06-06 23:52 UTC, zpr-ucsb commented
The riderId in the IndividualRidersClass is now no longer an array. All of the tests have been updated to reflect this. Some roles on the back end individualRidersController class have been changed to no longer be allowed by the USER role but instead the RIDER and DRIVER roles

2023-06-07 15:10 UTC, pconrad approved these changes
LGTM

2023-06-07 15:12 UTC, merged