jt-fixed raw json display on profile page
ucsb-cs156-s23/proj-gauchoride-s23-5pm-1 pull request #37
Opened 2023-06-01 00:40 UTC by TG6S85

Tested locally to ensure frontend works (without displaying raw code). Will add more details in the future.

2023-06-01 22:25 UTC, TG6S85 commented
Ok, basically, fixed the profilepage.test file, added 2 more fixtures to currentUserFixtures (one as a driver, one as a rider), and beautified the actual frontend page.

2023-06-04 19:04 UTC, pconrad requested changes
Commented out code needs to be cleaned up

2023-06-04 19:04 UTC, pconrad commented on frontend/src/main/pages/ProfilePage.js
> +//   const emailVerified = currentUser.root.user.emailVerified;
No commented out code in PRs please

2023-06-04 19:04 UTC, pconrad commented on frontend/src/main/pages/ProfilePage.js
> +          {/* This is supposed to be pronouns */}
No commented out code in PRs please, unless the intention is to say: "here is where pronouns will go".

But that might be better communicated in a separate Draft Pr than in a PR that's going into main.

2023-06-04 19:04 UTC, pconrad commented on frontend/src/main/pages/ProfilePage.js
> +          {/* <p className="lead text-muted">{currentUser.root.user.emailVerified ? "Yes": ""}</p> */}
No commented out code in PRs to main.

It's fine to have commented out code in a draft PR, or in work in progress, but by the time code goes to main, you need to commit: is it in, or it is out?

2023-06-04 19:04 UTC, pconrad commented on frontend/src/main/pages/ProfilePage.js
> +          {/* <p className="lead text-muted">{email}</p> */}
See above.

2023-06-04 19:04 UTC, pconrad commented on frontend/src/tests/pages/ProfilePage.test.js
> +        // expect(getByTestId("role-badge-admin")).toBeInTheDocument();
Please address the commented out code.

2023-06-04 19:04 UTC, pconrad commented on frontend/src/tests/pages/ProfilePage.test.js
> +        // expect(getByTestId("role-badge-member")).toBeInTheDocument();
see above

2023-06-04 19:04 UTC, pconrad commented on frontend/src/tests/pages/ProfilePage.test.js
> +        // expect(getByTestId("role-badge-member")).toBeInTheDocument();
see above

2023-06-04 19:06 UTC, pconrad commented
This is a frontend PR, so please follow the guidelines previously announced in this thread:
* https://ucsb-cs156-s23.slack.com/archives/C050779M19P/p1685400785702049

2023-06-06 21:21 UTC, TG6S85 commented on frontend/src/main/pages/ProfilePage.js
> +//   const emailVerified = currentUser.root.user.emailVerified;
Noted, has been taken care of

2023-06-06 21:23 UTC, TG6S85 commented on frontend/src/main/pages/ProfilePage.js
> +          {/* This is supposed to be pronouns */}
Noted, was planning on adding the pronoun feature once pronoun PR is merged, will be wary about this. I might make a comment so it's easier for future gen to understand the vision if that is ok.

2023-06-06 21:24 UTC, TG6S85 commented on frontend/src/tests/pages/ProfilePage.test.js
> +        // expect(getByTestId("role-badge-admin")).toBeInTheDocument();
Noted and addressed.

2023-06-07 02:08 UTC, merged