ef - add user pronouns, change pronouns endpoint, and test
ucsb-cs156-s23/proj-gauchoride-s23-5pm-1 pull request #38
Opened 2023-06-01 02:27 UTC by EKF626

In this PR, we create a new variable for the user class, String pronouns, and an endpoint to change it. To test, use swagger to change the pronouns of specific users.

2023-06-01 21:16 UTC, TG6S85 submitted a review, later dismissed
Looks good!

2023-06-01 21:53 UTC, andrewpengucsb requested changes, later dismissed

2023-06-01 21:53 UTC, andrewpengucsb commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/UsersController.java
> +
I feel like there is a slight mismatch where this method is under the users (admin only) controller but is functionality that every user should be able to use (which I assume is why there is no preauthorize). 

You may be able to put this in the userinfocontroller.

Additionally, right now any user can change any other user's pronoun which may cause issues

2023-06-06 19:21 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/UsersController.java
> +
I agree... ideally a user can change their own pronouns.

This is typically done by having a PUT endpoint with limited functionality (e.g. pronouns only) where you don't pass in an id, just a new value for pronouns (or an object with new values for the subset of fields that are user changeable, which could initally just be pronouns).  The id isn't passed in; it would be taken from the variable currentUser.

This is an easy fix; I can walk you through it in class today if needed.

*It could later include preferred name; that could be initialized from the Google information, but than overridable by the user; but that's a whole other user story.

2023-06-06 22:24 UTC, TG6S85 approved these changes, later dismissed
Looks good! I don't see any issues.

2023-06-06 23:01 UTC, pconrad requested changes
There are a couple of small cleanup items, but otherwise this looks good to go.

2023-06-06 23:01 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/UserInfoController.java
> +
Do we still need this?

2023-06-06 23:01 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/gauchoride/controllers/UserInfoControllerTests.java
> +
Are the changes to this file still needed?

2023-06-08 00:33 UTC, merged