ve- added RiderForm, RiderForm stories, RiderForm test and riderFixtures
ucsb-cs156-s23/proj-gauchoride-s23-5pm-1 pull request #42
Opened 2023-06-02 22:02 UTC by vikram-elango

Files added: RiderForm.js, RiderForm.test.js, riderFixtures.js, RiderForm.stories.js
In this PR, I added the form the rider will use to create a ride request. I also added it's test file as well as stories to view the form. 
The screenshot is below:

<img width="1230" alt="Screenshot 2023-06-02 at 3 01 16 PM" src="https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-1/assets/83794714/60f6365b-8b7f-415c-902e-942a99e40f84">

2023-06-04 19:15 UTC, pconrad requested changes
This PR description currently has a screenshot but it does not have a link to the storybook entry, which is here:

https://ucsb-cs156-s23.github.io/proj-gauchoride-s23-5pm-1/prs/42/storybook/?path=/story/components-rider-riderform--default

Please put the storybook link into your PR description when you have a frontend change.  

Please don't make the code reviewer have to go look for it.

2023-06-04 19:19 UTC, pconrad requested changes
Please add link to storybook, and consider renaming the form and fixtures as explained below.

2023-06-04 19:19 UTC, pconrad commented on frontend/src/fixtures/riderFixtures.js
> +    ],
This may seem picky, but it turns out that it really matters:

You've called the fixtures "riderFixtures" and you've called the form "RiderForm".

That name implies that we are doing operations on a Rider.

But that's not the case.  These are fixtures for a Ride object.

This is clear from the name of the variables: `oneRide`, `threeRides`, etc.

Please consider renaming this to `rideFixtures`, and renaming the form to `RideForm`.

It may not seem like it would matter that much.  But here's the thing: once you shift your thinking to how long this code is going to live, and how many other programmers are going to have to work with it over the coming year, you can be begin to see how a mismatch between a name and the contents of a file create confusion that makes the code harder to work with.

Naming things well (and refactoring code with misleading names) is one of the most important things we can do to promote quality code.

So I am going to ask you to fix this.

2023-06-04 21:21 UTC, vikram-elango commented on frontend/src/fixtures/riderFixtures.js
> +    ],
Hello Professor Conrad, I have made the above changes. I renamed RiderForm to RideForm and riderFixtures to rideFixtures

2023-06-06 19:07 UTC, pconrad commented on frontend/src/main/components/Ride/RideForm.js
> +            </Form.Group>
This would be better as a dropdown with the days of the week, so that users don't enter "Foobar" for example.

2023-06-06 19:13 UTC, pconrad requested changes
Some better validation on the day of week and start/end time would be useful.

If you switch to a drop down for day validation isn't needed there.

There almost might be a a time picker available somewhere.

2023-06-06 19:13 UTC, pconrad commented on frontend/src/main/components/Ride/RideForm.js
> +
But if you don't make this a dropdown, at least use a validation pattern like this: (you may have to fix minor syntax errors):
```suggestion
     pattern: /^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)$/i,
```

See also: https://www.react-hook-form.com/api/useform/register

2023-06-06 19:13 UTC, pconrad commented on frontend/src/main/components/Ride/RideForm.js
> +
Validate this input with a regular expression of some kind.  This is a best guess, not guaranteed to be correct:

```suggestion
 pattern: /(01|02|03|04|05|06|07|08|09|10|11|12):[0-5][0-9][AP]M/,
```

https://www.react-hook-form.com/api/useform/register

2023-06-06 19:13 UTC, pconrad commented on frontend/src/main/components/Ride/RideForm.js
> +
Validate format as above.

2023-06-06 19:16 UTC, pconrad commented
Example of a time picker: https://github.com/MEddarhri/react-ios-time-picker?ref=reactjsexample.com

2023-06-06 22:13 UTC, TG6S85 approved these changes
Commented-out code might be an issue, but I think otherwise it looks good!

2023-06-07 15:19 UTC, pconrad requested changes
Please restore the commented out line, and refactor the testid instances to use it.

2023-06-07 15:19 UTC, pconrad commented on frontend/src/main/components/Ride/RideForm.js
> +                        data-testid={"RideForm-id"}
```suggestion
                        data-testid={`${testid}-id`}
```
Once you uncomment the line above

2023-06-07 15:19 UTC, pconrad commented on frontend/src/main/components/Ride/RideForm.js
> +                    data-testid={"RideForm-day"}
```suggestion
                    data-testid={`${testid}-day`}
```

2023-06-07 15:19 UTC, pconrad commented on frontend/src/main/components/Ride/RideForm.js
> +                    data-testid={"RideForm-start"}
```suggestion
                    data-testid={`${testid}-start`}
```

2023-06-07 15:19 UTC, pconrad commented on frontend/src/main/components/Ride/RideForm.js
> +                    data-testid={"Ride-end"}
```suggestion
                    data-testid={`${testid}-end`}
```

2023-06-07 15:19 UTC, pconrad commented on frontend/src/main/components/Ride/RideForm.js
> +                    data-testid={"RideForm-pickupLocation"}
```suggestion
                    data-testid={`${testid}-pickupLocation`}
```

2023-06-07 15:19 UTC, pconrad commented on frontend/src/main/components/Ride/RideForm.js
> +                    data-testid={"RideForm-dropoffLocation"}
```suggestion
                    data-testid={`${testid}-dropoffLocation`}
```

2023-06-07 15:19 UTC, pconrad commented on frontend/src/main/components/Ride/RideForm.js
> +                data-testid={"RideForm-submit"}
```suggestion
                data-testid={`${testid}-submit`}
```

2023-06-07 15:19 UTC, pconrad commented on frontend/src/main/components/Ride/RideForm.js
> +                data-testid={"RideForm-cancel"}
```suggestion
                data-testid={`${testid}-cancel`}
```

2023-06-07 15:19 UTC, pconrad commented on frontend/src/tests/components/Ride/RideForm.test.js
> +    expect(await screen.findByTestId(`${testId}-id`)).toBeInTheDocument();
This shows the same pattern that I'm encouraging you to use in the main code.

2023-06-07 23:43 UTC, pconrad approved these changes
LGTM!

2023-06-07 23:45 UTC, merged