Vikram ride create page
ucsb-cs156-s23/proj-gauchoride-s23-5pm-1 pull request #47
Opened 2023-06-06 20:47 UTC by vikram-elango

still have to do

2023-06-06 23:00 UTC, TG6S85 requested changes
Looks good, seems that it is passing all tests, line 19 rideform.js has a commented piece of code.

2023-06-06 23:16 UTC, TG6S85 submitted a review, later dismissed

2023-06-07 19:04 UTC, TG6S85 submitted a review, later dismissed
Looks good!

2023-06-07 23:47 UTC, pconrad approved these changes
LGTM.   Will wait on CI/CD to merge because I had to resolve a couple of merge conflicts.

2023-06-08 00:11 UTC, merged